services:
  db:
    image: postgres:16-alpine
    container_name: finance_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  api:
    build: .
    container_name: finance_api
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "ls -l && python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
