# Generated by Django 5.1.6 on 2025-02-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_category_is_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='amount',
            new_name='balance',
        ),
    ]
